<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="about.aspx.vb" Inherits="about" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>Having observed people helping one another in friendly, social, and trusting communal ways on the Internet via theWELL, MindVox and Usenet, and feeling isolated as a relative newcomer to San Francisco, Craigslist founder Craig Newmark decided to create something similar for local events. In early 1995, he began an email distribution list to friends. Most of the early postings were submitted by Newmark and were notices of social events of interest to software and Internet developers living and working in the San Francisco Bay Area.</p>
<p>Soon, word of mouth led to rapid growth. The number of subscribers and postings grew rapidly. There was no moderation and Newmark was surprised when people started using the mailing list for non-event postings. People trying to get technical positions filled found that the list was a good way to reach people with the skills they were looking for. This led to the addition of a category for "jobs". User demand for more categories caused the list of categories to grow. The initial technology encountered some limits, so by June 1995 majordomo had been installed and the mailing list "Craigslist" resumed operations. Community members started asking for a web interface. Craig registered "craigslist.org", and the website went live in 1996.</p>
<p>By early 1998, Newmark still thought his career was as a software engineer ("hardcore java programmer") and that Craigslist was a cool hobby that was getting him invited to the best parties for geeks and nerds. In the fall of 1998, the name "List Foundation" was introduced and Craigslist started transitioning to the use of this name. In April 1999, when Newmark learned of other organizations called "List Foundation", the use of this name was dropped. Craigslist incorporated as a private for-profit company in 1999. Around the time of these events, Newmark realized that the site was growing so fast that he could stop working as a software engineer and work full-time running Craigslist. By April 2000, there were nine employees working out of Newmark's apartment in San Francisco. </p>

    </asp:Content>

